/*
 * introspect.ts — read live game state straight out of the Z-machine memory.
 *
 * The renderer needs to know which room the player is in. The Z-machine v3
 * status line is generated by the interpreter from the object held in global
 * variable 16, so that global IS the current room object. We read it directly
 * (stable numeric identity), and pair it with the decoded status-line name to
 * resolve the specific ZIL room. We also expose the object tree so we can list
 * what's currently in the room (props, NPCs) and detect darkness.
 *
 * Z-machine v3 layout (Standard 1.1):
 *   header 0x0A = object table addr, 0x0C = globals addr, 0x0E = static base
 *   object table = 31 property-default words (62 bytes), then 9-byte entries:
 *     [4 attribute bytes][parent][sibling][child][2-byte prop table addr]
 *   global G (16..255) word at globalsAddr + 2*(G-16)
 */

export interface LiveState {
  /** Object number of the current room (global 16). */
  roomObjNum: number;
  /** Object numbers contained directly in the room (props, NPCs). */
  contents: number[];
  /** True if the room object lacks the lit attribute and nothing lit is carried. */
  // (computed in roomState where flag data is available)
}

const OBJ_ENTRY = 9; // bytes per v3 object entry
const PROP_DEFAULTS = 31 * 2; // 62 bytes of property defaults

export class Introspector {
  private m: any;
  private objTable: number;
  private globals: number;

  constructor(private vm: any) {
    this.m = vm.m;
    this.objTable = this.m.getUint16(0x0a);
    this.globals = this.m.getUint16(0x0c);
  }

  /** Word value of a global variable (16..255). */
  global(num: number): number {
    return this.m.getUint16(this.globals + 2 * (num - 16));
  }

  /** Address of an object's 9-byte entry. */
  private objAddr(obj: number): number {
    return this.objTable + PROP_DEFAULTS + (obj - 1) * OBJ_ENTRY;
  }

  parentOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 4);
  }
  siblingOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 5);
  }
  childOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 6);
  }

  /** Direct children (contents) of an object, as object numbers. */
  childrenOf(obj: number): number[] {
    const out: number[] = [];
    let c = this.childOf(obj);
    let guard = 0;
    while (c !== 0 && guard++ < 256) {
      out.push(c);
      c = this.siblingOf(c);
    }
    return out;
  }

  /** The current room object number (global 16 = the v3 status-line object). */
  currentRoom(): number {
    return this.global(16);
  }

  /** Whether object has a given attribute bit set (0..31). */
  hasAttr(obj: number, attr: number): boolean {
    const byte = this.m.getUint8(this.objAddr(obj) + (attr >> 3));
    return (byte & (0x80 >> (attr & 7))) !== 0;
  }

  snapshot(): LiveState {
    const room = this.currentRoom();
    return {
      roomObjNum: room,
      contents: room ? this.childrenOf(room) : [],
    };
  }
}
