/*
 * introspect.ts — read live game state straight out of the Z-machine memory.
 *
 * The renderer needs to know which room the player is in. The Z-machine v3
 * status line is generated by the interpreter from the object held in global
 * variable 16, so that global IS the current room object. We read it directly
 * (stable numeric identity), and pair it with the decoded status-line name to
 * resolve the specific ZIL room. We also expose the object tree so we can list
 * what's currently in the room (props, NPCs) and detect darkness.
 *
 * Z-machine v3 layout (Standard 1.1):
 *   header 0x0A = object table addr, 0x0C = globals addr, 0x0E = static base
 *   object table = 31 property-default words (62 bytes), then 9-byte entries:
 *     [4 attribute bytes][parent][sibling][child][2-byte prop table addr]
 *   global G (16..255) word at globalsAddr + 2*(G-16)
 */

export interface LiveState {
  /** Object number of the current room (global 16). */
  roomObjNum: number;
  /** Object numbers contained directly in the room (props, NPCs). */
  contents: number[];
  /** True if the room object lacks the lit attribute and nothing lit is carried. */
  // (computed in roomState where flag data is available)
}

const OBJ_ENTRY = 9; // bytes per v3 object entry
const PROP_DEFAULTS = 31 * 2; // 62 bytes of property defaults

// Z-text v3 alphabets (Standard 1.1 §3). A2[0] is the 10-bit escape, A2[1] newline.
const A0 = "abcdefghijklmnopqrstuvwxyz";
const A1 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const A2 = "??0123456789.,!?_#'\"/\\-:()";

export class Introspector {
  private m: any;
  private objTable: number;
  private globals: number;
  private abbrevs: number;
  private nameCache = new Map<number, string>();

  constructor(private vm: any) {
    this.m = vm.m;
    this.objTable = this.m.getUint16(0x0a);
    this.globals = this.m.getUint16(0x0c);
    this.abbrevs = this.m.getUint16(0x18);
  }

  /** Word value of a global variable (16..255). */
  global(num: number): number {
    return this.m.getUint16(this.globals + 2 * (num - 16));
  }

  /** Address of an object's 9-byte entry. */
  private objAddr(obj: number): number {
    return this.objTable + PROP_DEFAULTS + (obj - 1) * OBJ_ENTRY;
  }

  parentOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 4);
  }
  siblingOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 5);
  }
  childOf(obj: number): number {
    return this.m.getUint8(this.objAddr(obj) + 6);
  }

  /** Direct children (contents) of an object, as object numbers. */
  childrenOf(obj: number): number[] {
    const out: number[] = [];
    let c = this.childOf(obj);
    let guard = 0;
    while (c !== 0 && guard++ < 256) {
      out.push(c);
      c = this.siblingOf(c);
    }
    return out;
  }

  /** The current room object number (global 16 = the v3 status-line object). */
  currentRoom(): number {
    return this.global(16);
  }

  /** All descendants of an object (children, grandchildren, …), bounded. */
  descendantsOf(obj: number, depth = 4): number[] {
    if (depth <= 0) return [];
    const out: number[] = [];
    for (const c of this.childrenOf(obj)) {
      out.push(c, ...this.descendantsOf(c, depth - 1));
      if (out.length > 128) break; // corrupt-tree guard
    }
    return out;
  }

  /** Decode a Z-text string at a byte address (v3, with abbreviations). */
  private ztext(addr: number, allowAbbrev = true): string {
    const z: number[] = [];
    for (let a = addr, guard = 0; guard < 128; a += 2, guard++) {
      const w = this.m.getUint16(a);
      z.push((w >> 10) & 31, (w >> 5) & 31, w & 31);
      if (w & 0x8000) break;
    }
    let out = "", alpha = 0;
    for (let i = 0; i < z.length; i++) {
      const c = z[i];
      if (c === 0) { out += " "; alpha = 0; }
      else if (c <= 3) {
        if (allowAbbrev && i + 1 < z.length) {
          const entry = 32 * (c - 1) + z[++i];
          out += this.ztext(2 * this.m.getUint16(this.abbrevs + 2 * entry), false);
        }
        alpha = 0;
      } else if (c === 4) alpha = 1;
      else if (c === 5) alpha = 2;
      else {
        if (alpha === 2 && c === 6) { // 10-bit ZSCII escape
          if (i + 2 < z.length) { out += String.fromCharCode(((z[i + 1] << 5) | z[i + 2]) & 1023); i += 2; }
        } else out += (alpha === 1 ? A1 : alpha === 2 ? A2 : A0)[c - 6];
        alpha = 0;
      }
    }
    return out;
  }

  /** An object's short name ("brown sack"), decoded from its property table. */
  shortName(obj: number): string {
    const hit = this.nameCache.get(obj);
    if (hit !== undefined) return hit;
    let name = "";
    try {
      const props = this.m.getUint16(this.objAddr(obj) + 7);
      if (this.m.getUint8(props) > 0) name = this.ztext(props + 1);
    } catch { /* unreadable — leave blank */ }
    this.nameCache.set(obj, name);
    return name;
  }

  /** Whether object has a given attribute bit set (0..31). */
  hasAttr(obj: number, attr: number): boolean {
    const byte = this.m.getUint8(this.objAddr(obj) + (attr >> 3));
    return (byte & (0x80 >> (attr & 7))) !== 0;
  }

  snapshot(): LiveState {
    const room = this.currentRoom();
    return {
      roomObjNum: room,
      contents: room ? this.childrenOf(room) : [],
    };
  }
}
